### PR TITLE
PdoException is not catched

### PR DESCRIPTION
**Pull request by cv65kr**
Because you are using `Doctrine\DBAL\Exception` PdoException is not catched. This change is similar to approach from previous version of library for Doctrine 2.X

https://github.com/facile-it/doctrine-mysql-come-back/issues/63

### CODE REVIEW

**Comment by Jean85** [comment]
Thank you for opening the PR, but this is unmergeable without tests, a green build and a changelog entry.

**Comment by tourze** [comment]
It is better to catch "\Doctrine\DBAL\Exception|\PDOException".

**Comment by kibertoad** [comment]
@cv65kr Do you plan to finish this?

**Comment by cv65kr** [comment]
@kibertoad I will try to update PR in this week.

**Comment by kibertoad** [comment]
@cv65kr Awesome, thank you!

**Comment by kibertoad** [comment]
@cv65kr Any chance you could finish this?

**Comment by cv65kr** [comment]
@kibertoad I figured out that library supports mysqli extension as well and is not that simple to cover both cases. Because docker image contains mysqli and pdo together so you are not able to test it properly e.g. what's happened if extension is not installed. PDO case is tested and in my project I am using own this release. Honestly I don't have a time right now, to invest it for Mysqli extension which I am not using and most of modern frameworks rely on PDO. Authors are also not interested in this library since issue was opened couple months ago.

My suggestion is if you really need it, pls prepare your own release of my PR and when I find time will try to take care about that.

**Comment by Jean85** [comment]
Closing as ported in #68

**Pull request closed without merging**
