### PR TITLE
WIP: Better code consistency

### PR DESCRIPTION
**Pull request by thomasvargiu**
Implemented required methods in `ConnectionInterface` used in ` ConnectionTrait`.

This could be considered a BC.

### CODE REVIEW

**Review by Jean85 — CHANGES_REQUESTED** [review]
This is surely a BC, we shouldn't implement it like this, at least not in this first step.

We can:
*  create a new `interface RetriableConnectionInterface extends ConnectionInterface`
* add the new methods there
* deprecate the current `ConnectionInterface`
* apply the new interface to our implementations
* drop the old `ConnectionInterface` in the next major

**Comment by Jean85** [comment]
We should plan for a new major anyway, since DBAL 3.0 has too many breaking changes...

**Comment by thomasvargiu** [comment]
Yes, in my mind this should be a fisr refactor in order to start writing a new version compatible with dbal v3 in order to make it easier to migrate. I'll try to make those changes.

**Comment by thomasvargiu** [comment]
Working on it I was thinking that missed methods on `ConnectionInterface` can be considered a bug, because we always need those method implementations in our classes, implementations provided by the `ConnectionTrait`.
Changing our implementations to use the new interface can be considered a BC Break too, because no user's `ConnectionInterface` implementations can be used anymore.
It can be legit to me to just warn users that there is a possible BC Break in our minor release.
@Jean85 What do you think?

**Comment by Jean85** [comment]
Wouldn't a major bump work as a nice "warning"? We would also get the nice side effect of releasing a future 3.0 compatible with DBAL 3.0.. :smile:

**Comment by Jean85** [comment]
Closing since DBAL v2 is not dropped, and our v2 is nearly ready.

**Pull request closed without merging**
